version: "3.8"
services:
  postgres:
    image: postgis/postgis:15-3.3
    container_name: postgres_ciudadania360
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Aqmdla04
      POSTGRES_DB: ciudadania360
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    restart: unless-stopped
volumes:
  postgres_data:
