server:
  port: 8082
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ciudadania360
    username: postgres
    password: Aqmdla04
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: ciudadano
    open-in-view: false
  flyway:
    enabled: true
    schemas: ciudadano
    locations: classpath:db/migration
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth.local/realms/ciudadania360
management:
  endpoints:
    web:
      exposure:
        include: health,info
