server:
  port: 8082
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ciudadania360
    username: postgres
    password: Aqmdla04
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    schemas: ciudadano
    default_schema: ciudadano
    locations: classpath:db/migration
    baseline-on-migrate: false
    validate-on-migrate: true
    clean-disabled: false
    clean-on-validation-error: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth.local/realms/ciudadania360
management:
  endpoints:
    web:
      exposure:
        include: health,info
