server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: ciudadania360
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/ciudadania360}
    username: ${SPRING_DATASOURCE_USERNAME:ciudadania}
    password: ${SPRING_DATASOURCE_PASSWORD:ciudadania}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:init-db
    schemas: ciudadano, tramitacion, comunicaciones, videoconferencia, informacion, roles, ia, interno, shared
    default-schema: ciudadano
    baseline-on-migrate: true
    validate-on-migrate: true
  security:
    security:
      oauth2:
        resourceserver:
          enabled: false
logging:
  level:
    root: INFO
    com.ciudadania360: DEBUG
    org.springframework.security: INFO
    org.hibernate.spatial: WARN
    org.springframework.security.authentication: WARN
    org.springframework.security.web: WARN
    org.apache.cxf: INFO

cors:
  allowed-origins: "*"
  allowed-methods: GET,POST,PUT,DELETE,PATCH,OPTIONS

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui
    deep-linking: true
    display-request-duration: true
    filter: true
    operations-sorter: alpha
    tags-sorter: alpha
    doc-expansion: none

# Configuración AyWebFwk - Servicios Web SOAP para Docker
cxf:
  path: /services

# Configuración de servicios web
webservice:
  ciudadano:
    endpoint: /ciudadano
    namespace: http://ciudadania360.com/aywebfwk/ws/ciudadano
    service-name: CiudadanoWebService
    port-name: CiudadanoWebServicePort
  tramitacion:
    endpoint: /tramitacion
    namespace: http://ciudadania360.com/aywebfwk/ws/tramitacion
    service-name: TramitacionWebService
    port-name: TramitacionWebServicePort
  comunicaciones:
    endpoint: /comunicaciones
    namespace: http://ciudadania360.com/aywebfwk/ws/comunicaciones
    service-name: ComunicacionesWebService
    port-name: ComunicacionesWebServicePort